name: Update contact list
on:
  push:
    branches: 
      - "main"
  schedule:
    - cron: 0 7 * * 1  # Every monday at 7 am

jobs:
  run:
    name: Job - Update contact list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      
      - name: Lint with black
        run: |
          black ./scripts/

      - name: Run crawlers
        run: |
          python3 ./scripts/

      - name: Commit contacts .csv
        uses: EndBug/add-and-commit@v7
        with:
          author_name: bot
          author_email: thom.blizz@gmail.com
          message: 'Update politicians contact list'
          add: '*'
